name: Build and Release APK

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build APK
        run: ./gradlew assembleRelease

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./app/build/outputs/apk/release/app-release-unsigned.apk"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
