name: Build and Release APK

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build APK
        run: ./gradlew assembleRelease

      - uses: Tlaster/android-sign@v1.2.2
        name: Sign app APK
        with:
            releaseDirectory: |
              "./app/build/outputs/apk/release/"
            signingKeyBase64: ${{ secrets.SIGNING_KEY }}
            output: "./app/build/outputs/apk/release/wig.apk"
            alias: ${{ secrets.ALIAS }}
            keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./app/build/outputs/apk/release/wig.apk"
          tag: v0.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
